# Generated by Django 5.0.14 on 2026-08-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="academic_year",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
