# Generated by Django 5.2.6 on 2026-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0002_sprint_academic_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("collecting", "Collecting"),
                    ("processing", "Processing"),
                    ("reviewing", "Reviewing"),
                    ("scoring", "Scoring"),
                    ("baseline_pending", "Baseline Pending"),
                    ("baseline_approved", "Baseline Approved"),
                    ("report_ready", "Report Ready"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
