import uuid

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.scoring.constants import PILLAR_CHOICES


class Recommendation(models.Model):
    """One actionable suggestion for a sprint, generated by
    apps.recommendations.services from real gap/fact/pillar-score data (see
    that module's three generators) and optionally edited by an InGage
    consultant afterward. Nothing here is invented independent of the
    sprint's own data -- `description` always states the specific data point
    that triggered it, and `source_gap`/`supporting_facts` link back to the
    exact records so the recommendation stays traceable and explainable.
    """
    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        ACCEPTED = 'accepted', 'Accepted'
        EDITED = 'edited', 'Edited'
        HIDDEN = 'hidden', 'Hidden'
        COMPLETED = 'completed', 'Completed'

    class Priority(models.TextChoices):
        BLOCKING = 'blocking', 'Blocking'
        HIGH = 'high', 'High'
        MEDIUM = 'medium', 'Medium'
        OPTIONAL = 'optional', 'Optional'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sprint = models.ForeignKey('sprints.Sprint', on_delete=models.CASCADE, related_name='recommendations')
    title = models.CharField(max_length=255)
    description = models.TextField()
    #: Human-readable citation of what triggered this recommendation (e.g.
    #: "Missing Document: NAAC SSR") -- a display string, kept separate from
    #: `source_gap` below for the same reason apps.gaps derives owner_role
    #: rather than storing it: this is what the (unmodified) frontend's
    #: RecommendationsReview.tsx renders directly.
    trigger_gap = models.TextField(blank=True)
    #: The actual gap record trigger_gap describes, if any -- lets
    #: services.py dedupe regeneration by record rather than by re-parsing
    #: the display string.
    source_gap = models.ForeignKey(
        'gaps.GapItem', on_delete=models.SET_NULL, null=True, blank=True, related_name='recommendations',
    )
    supporting_facts = models.ManyToManyField(
        'facts.ExtractedFact', blank=True, related_name='recommendations',
    )
    pillar = models.CharField(max_length=64, choices=PILLAR_CHOICES, blank=True)
    owner_role = models.CharField(max_length=50, blank=True)
    priority = models.CharField(max_length=20, choices=Priority.choices, default=Priority.MEDIUM)
    timeline = models.CharField(max_length=100, blank=True)
    #: Points this recommendation would add to the sprint's overall CRI (same
    #: 0-100 bound as PillarScore.raw_score/ScoringRun.overall_cri) if acted
    #: on -- validated both here and on PATCH (see
    #: RecommendationUpdateSerializer.validate_expected_cri_lift).
    expected_cri_lift = models.FloatField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100)],
    )
    #: The InGage support/consulting offering that pairs with this
    #: recommendation (e.g. a remediation workshop) -- free text, since the
    #: catalog of offerings is not part of this task's scope.
    support_offering = models.TextField(blank=True)
    #: Freeform notes a consultant adds when reviewing/editing -- distinct
    #: from `description`, which is the recommendation itself.
    consultant_notes = models.TextField(blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.DRAFT)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='+',
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='+',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.pillar}: {self.title}'
