# Generated by Django 5.0.14 on 2026-08-17 13:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facts", "0002_alter_extractedfact_value_and_more"),
        ("gaps", "0001_initial"),
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("trigger_gap", models.TextField(blank=True)),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("governance_strategy", "Governance & Strategy"),
                            (
                                "curriculum_academic_readiness",
                                "Curriculum & Academic Readiness",
                            ),
                            ("faculty_ai_capability", "Faculty AI Capability"),
                            ("student_ai_readiness", "Student AI Readiness"),
                            (
                                "infrastructure_digital_capability",
                                "Infrastructure & Digital Capability",
                            ),
                            ("research_innovation", "Research & Innovation"),
                            ("industry_placement", "Industry & Placement Outcomes"),
                            ("evidence_quality", "Evidence Quality & Data Confidence"),
                        ],
                        max_length=64,
                    ),
                ),
                ("owner_role", models.CharField(blank=True, max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("blocking", "Blocking"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("optional", "Optional"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("timeline", models.CharField(blank=True, max_length=100)),
                (
                    "expected_cri_lift",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("support_offering", models.TextField(blank=True)),
                ("consultant_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("accepted", "Accepted"),
                            ("edited", "Edited"),
                            ("hidden", "Hidden"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_gap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="gaps.gapitem",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "supporting_facts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recommendations",
                        to="facts.extractedfact",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
