# Generated by Django 5.0.14 on 2026-08-17 13:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pillar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="ScoringRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calculation_version", models.CharField(max_length=64)),
                ("overall_cri", models.FloatField(default=0)),
                ("overall_confidence", models.FloatField(default=0)),
                ("evidence_count", models.PositiveIntegerField(default=0)),
                ("gap_count", models.PositiveIntegerField(default=0)),
                ("pillar_snapshot", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_runs",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PillarCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                ("fact_field_keys", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="scoring.pillar",
                    ),
                ),
            ],
            options={
                "ordering": ["pillar", "key"],
                "unique_together": {("pillar", "key")},
            },
        ),
        migrations.CreateModel(
            name="PillarScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_score", models.FloatField(default=0)),
                ("weighted_score", models.FloatField(default=0)),
                ("confidence_score", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("at_risk", "At Risk"),
                            ("developing", "Developing"),
                            ("strong", "Strong"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("evidence_count", models.PositiveIntegerField(default=0)),
                ("gap_count", models.PositiveIntegerField(default=0)),
                ("calculation_version", models.CharField(blank=True, max_length=64)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="scoring.pillar",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillar_scores",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["pillar__display_order", "pillar__key"],
                "unique_together": {("sprint", "pillar")},
            },
        ),
    ]
