# Generated by Django 5.0.14 on 2026-08-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
