# Generated by Django 5.2.6 on 2026-09-03 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_institution_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="current_ai_usage",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="digital_maturity_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Level 1 — Manual"),
                    (2, "Level 2 — Partial Digital"),
                    (3, "Level 3 — Integrated"),
                    (4, "Level 4 — Data-Driven"),
                    (5, "Level 5 — AI-Enabled"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="faculty_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="priorities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="institution",
            name="student_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InstitutionLeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaders",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[("legacy", "Legacy"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("head_name", models.CharField(blank=True, max_length=255)),
                ("faculty_count", models.PositiveIntegerField(default=0)),
                ("student_count", models.PositiveIntegerField(default=0)),
                ("program_count", models.PositiveIntegerField(default=0)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution", "name"),
                        name="unique_department_name_per_institution",
                    )
                ],
            },
        ),
    ]
