# Generated by Django 5.0.14 on 2026-08-17 11:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("field_key", models.CharField(max_length=150)),
                ("value", models.JSONField()),
                ("normalized_value", models.JSONField(blank=True, null=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("percentage", "Percentage"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("currency", "Currency"),
                            ("list", "List"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("governance_strategy", "Governance & Strategy"),
                            (
                                "curriculum_academic_readiness",
                                "Curriculum & Academic Readiness",
                            ),
                            ("faculty_ai_capability", "Faculty AI Capability"),
                            ("student_ai_readiness", "Student AI Readiness"),
                            (
                                "infrastructure_digital_capability",
                                "Infrastructure & Digital Capability",
                            ),
                            ("research_innovation", "Research & Innovation"),
                            ("industry_placement", "Industry & Placement Outcomes"),
                            ("evidence_quality", "Evidence Quality & Data Confidence"),
                        ],
                        max_length=64,
                    ),
                ),
                ("owner_role", models.CharField(blank=True, max_length=50)),
                ("source_page", models.CharField(blank=True, max_length=50)),
                ("source_snippet", models.TextField(blank=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("confidence_reason", models.TextField(blank=True)),
                ("extraction_method", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("confirmed", "Confirmed"),
                            ("corrected", "Corrected"),
                            ("rejected", "Rejected"),
                            ("evidence_requested", "Evidence Requested"),
                        ],
                        default="extracted",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_facts",
                        to="documents.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactReviewHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("corrected", "Corrected"),
                            ("rejected", "Rejected"),
                            ("evidence_requested", "Evidence Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_value", models.JSONField()),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_history",
                        to="facts.extractedfact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fact review histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
