# Generated by Django 5.0.14 on 2026-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedfact",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="factreviewhistory",
            name="original_value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
