# Generated by Django 5.0.14 on 2026-08-17 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("sprints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("retrying", "Retrying"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("classifying_documents", "Classifying Documents"),
                            ("reading_pages", "Reading Pages"),
                            ("extracting_facts", "Extracting Facts"),
                            ("mapping_audit_fields", "Mapping Audit Fields"),
                            ("detecting_gaps", "Detecting Gaps"),
                            ("checking_conflicts", "Checking Conflicts"),
                            (
                                "preparing_review_workspace",
                                "Preparing Review Workspace",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_jobs",
                        to="documents.document",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_jobs",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
