# Generated by Django 5.2.6 on 2026-08-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionjob",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="extractionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("retrying", "Retrying"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
