# Generated by Django 5.0.14 on 2026-08-17 10:34

import apps.documents.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Document type must be a lowercase snake_case identifier, e.g. "naac_ssr".',
                                regex="^[a-z][a-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.documents.utils.document_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hex digest",
                        max_length=64,
                    ),
                ),
                ("owner_role", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("ocr_required", models.BooleanField(default=False)),
                ("ocr_warnings", models.JSONField(blank=True, default=list)),
                ("processing_status", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("checksum", ""), _negated=True),
                fields=("sprint", "checksum"),
                name="unique_document_checksum_per_sprint",
            ),
        ),
    ]
