# Generated by Django 5.2.6 on 2026-09-04 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0002_driveimportjob"),
        ("institutions", "0003_institution_current_ai_usage_and_more"),
        ("sprints", "0003_alter_sprint_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorDocumentIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vector_count", models.PositiveIntegerField(default=0)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_index",
                        to="documents.document",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_indexes",
                        to="institutions.institution",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_indexes",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vector document indexes",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["sprint", "status"], name="ix_vecidx_sprint_status"
                    )
                ],
            },
        ),
    ]
