# Generated by Django 5.0.14 on 2026-08-17 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("facts", "0002_alter_extractedfact_value_and_more"),
        ("sprints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GapItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gap_type",
                    models.CharField(
                        choices=[
                            ("missing_document", "Missing Document"),
                            ("unconfirmed_fact", "Unconfirmed Fact"),
                            ("conflict", "Conflict"),
                            ("stale_data", "Stale Data"),
                            ("low_confidence", "Low Confidence"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("governance_strategy", "Governance & Strategy"),
                            (
                                "curriculum_academic_readiness",
                                "Curriculum & Academic Readiness",
                            ),
                            ("faculty_ai_capability", "Faculty AI Capability"),
                            ("student_ai_readiness", "Student AI Readiness"),
                            (
                                "infrastructure_digital_capability",
                                "Infrastructure & Digital Capability",
                            ),
                            ("research_innovation", "Research & Innovation"),
                            ("industry_placement", "Industry & Placement Outcomes"),
                            ("evidence_quality", "Evidence Quality & Data Confidence"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("blocking", "Blocking"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("optional", "Optional"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("unavailable", "Unavailable"),
                            ("skipped", "Skipped"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gaps",
                        to="documents.document",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_fact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gaps",
                        to="facts.extractedfact",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gaps",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="gapitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_fact__isnull", False),
                    ("status__in", ["open", "in_progress"]),
                ),
                fields=("gap_type", "source_fact"),
                name="unique_active_gap_per_fact_and_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="gapitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("related_document__isnull", False),
                    ("source_fact__isnull", True),
                    ("status__in", ["open", "in_progress"]),
                ),
                fields=("gap_type", "related_document"),
                name="unique_active_gap_per_document_and_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="gapitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("related_document__isnull", True),
                    ("source_fact__isnull", True),
                    ("status__in", ["open", "in_progress"]),
                ),
                fields=("sprint", "gap_type", "title"),
                name="unique_active_gap_per_sprint_type_title",
            ),
        ),
    ]
