# Generated by Django 5.0.14 on 2026-08-18 09:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facts", "0002_alter_extractedfact_value_and_more"),
        ("gaps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gapitem",
            name="conflict_confidence",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="gapitem",
            name="conflict_fact_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="facts.extractedfact",
            ),
        ),
        migrations.AddField(
            model_name="gapitem",
            name="conflict_value_a",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gapitem",
            name="conflict_value_b",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
